---

# - src: ome.omero_common
#   version: 0.4.0
- name: omero_common
  src: https://github.com/pwalczysko/ansible-role-omero-common
  varsion: update-framework

# - src: ome.basedeps
#   version: 1.3.2
- name: basedeps
  src: https://github.com/pwalczysko/ansible-role-basedeps
  version: update-framework

# - src: ome.java
#   version: 2.2.0
- name: java
  src: https://github.com/khaledk2/ansible-role-java
  version: update_ansible

# - src: ome.python3_virtualenv
#   version: 0.2.0
- name: python3_virtualenv
  src: https://github.com/khaledk2/ansible-role-python3-virtualenv
  version: update_ansible_python

# - src: ome.ice
#   version: 4.4.4
- name: ice
  src: https://github.com/khaledk2/ansible-role-ice
  version: Updating_to_the_latest_ansible_version

# - src: ome.postgresql
#   version: 5.4.0
- name: postgresql
  src: https://github.com/pwalczysko/ansible-role-postgresql
  version: p312

# - src: ome.postgresql_client
#   version: 0.4.3
- name: postgresql_client
  src: https://github.com/khaledk2/ansible-role-postgresql-client
  version: update_ansible

# - src: ome.deploy_archive
#   version: 0.2.0
- name: deploy_archive
  src: https://github.com/pwalczysko/ansible-role-deploy-archive
  version: update-framework

# - src: ome.omero_server
#   version: 6.1.0
- name: omero_server
  src: https://github.com/pwalczysko/ansible-role-omero-server
  version: pythonvers-symlink-in-virtualenvrole

# - src: ome.omero_web
#   version: 5.1.1
- name: omero_web
  src: https://github.com/pwalczysko/ansible-role-omero-web
  version: p312

# - src: ome.nginx
#   version: 2.2.1
- name: nginx
  src: https://github.com/pwalczysko/ansible-role-nginx
  version: nginx-repo

# - src: ome.redis
#   version: 1.3.0
- name: redis
  src: https://github.com/khaledk2/ansible-role-redis
  version: update_Ansible

# - src: ome.selinux_utils
#   version: 2.1.1
- name: selinux_utils
  src: https://github.com/khaledk2/ansible-role-selinux-utils
  version: update_ansible

# - src: ome.versioncontrol_utils
#   version: 1.1.0
- name: versioncontrol_utils
  src: https://github.com/khaledk2/ansible-role-versioncontrol-utils
  version: update_ansible_version

# - src: ome.ssl_certificate
#   version: 0.5.0
- name: ssl_certificate
  src: https://github.com/khaledk2/ansible-role-ssl-certificate
  version: Update_ansibel

# - src: nfs_mount
#   version: 2.0.0
- name: nfs_mount
  src: https://github.com/khaledk2/ansible-role-nfs-mount
  version: update_ansibel

# - src: nfs_share
#   version: 1.0.0
- name: nfs_share
  src: https://github.com/pwalczysko/ansible-role-nfs-share
  version: upgrade-framework

# - src: iptables_raw
#   version: 0.4.0
- name: iptables_raw
  src: https://github.com/khaledk2/ansible-role-iptables-raw
  version: update_ansible

# - src: ome.cli_utils
#   version: 1.2.5
- name: cli_utils
  src: https://github.com/pwalczysko/ansible-role-cli-utils
  version: update-framework

# - src: ome.docker
#   version: 3.2.2
- name: docker
  src: https://github.com/khaledk2/ansible-role-docker
  version: update_ansible_ver

# - src: ome.postgresql_backup
#   version: 0.3.0
- name: postgresql_backup
  src: https://github.com/pwalczysko/ansible-role-postgresql-backup
  version: update-framework

# - src: ome.omero_user
#   version: 0.4.0
- name: omero_user
  src: https://github.com/pwalczysko/ansible-role-omero-user
  version: include

# - src: ome.lvm_partition
#   version: 1.2.0
- name: lvm_partition
  src: https://github.com/khaledk2/ansible-role-lvm-partition
  version: updater_ansible_version
